### ISSUE TITLE
Rate limit reached

### ISSUE THREAD

**Issue by scout247** [ayaka14732/ChatGPTAPIFree#9] opened 2023-03-08 08:42 UTC
it seems like the rate limit has been reached
![image](https://user-images.githubusercontent.com/44242146/223664829-4212c44c-988c-4410-a902-2873d2d27492.png)

**Comment by ayaka14732** [comment] 2023-03-12 07:02
Thanks for reporting! Closed as duplicate of #5

**Closed by ayaka14732** 2023-03-12 07:02 UTC
